langauge: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bdburns6389/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bdburns6389/docker-react npm run test
